import subprocess, re

print("=== DIFFERENTIATING /resources vs /books TAGS ===\n")

# ---------- /resources : FREE intent ----------
p = "backend/templates/resources.html"
c = open(p, encoding="utf-8").read()

c = re.sub(r'{% block title %}.*?{% endblock %}',
           '{% block title %}Free Cybersecurity Templates & GRC Starter Kit | GRCWithGaurav{% endblock %}', c, count=1, flags=re.DOTALL)
c = re.sub(r'{% block description %}.*?{% endblock %}',
           '{% block description %}Download free, ready-to-use GRC artifacts: ISO 27001 risk register, audit checklist, SOC interview questions, career roadmap and ATS resume check - built free by our tools, no signup.{% endblock %}', c, count=1, flags=re.DOTALL)
c = re.sub(r'<meta name="twitter:title" content="[^"]*">',
           '<meta name="twitter:title" content="Free Cybersecurity Templates & GRC Starter Kit | GRCWithGaurav">', c, count=1)
c = re.sub(r'<meta name="twitter:description" content="[^"]*">',
           '<meta name="twitter:description" content="Five free artifacts you can build today: risk register, audit checklist, interview prep, roadmap, resume check. No signup, no payment.">', c, count=1)

# rename the books cross-link card so the page reads "free first, paid next"
c = c.replace('<h3 style="margin-top:0">Ebooks &amp; Playbooks</h3>',
              '<h3 style="margin-top:0">Ready for the full playbooks?</h3>')
c = c.replace('Three practical playbooks for GRC and AI in security careers.',
              'Five practitioner playbooks and toolkits - $9 each, or all five for $35.')

# CollectionPage schema (free-collection signal)
if 'CollectionPage' not in c:
    ld = '''<script type="application/ld+json">
{"@context":"https://schema.org","@type":"CollectionPage","name":"Free Cybersecurity Templates & GRC Starter Kit","description":"Free, ready-to-use GRC artifacts generated by free tools.","url":"https://grcwithgaurav.com/resources"}
</script>
'''
    i = c.find('{% block head %}')
    e = c.find('{% endblock %}', i)
    c = c[:e] + ld + c[e:]

open(p, "w", encoding="utf-8").write(c)
print("[UPDATED] /resources -> free-templates intent")

# ---------- /books : BUY intent ----------
p = "backend/templates/books.html"
c = open(p, encoding="utf-8").read()

c = re.sub(r'{% block title %}.*?{% endblock %}',
           '{% block title %}Cybersecurity & GRC eBooks - 5 Playbooks, $9 Each or $35 Bundle | GRCWithGaurav{% endblock %}', c, count=1, flags=re.DOTALL)
c = re.sub(r'{% block description %}.*?{% endblock %}',
           '{% block description %}Buy practitioner eBooks by Gaurav Malhotra: Breaking Into GRC, AI Governance Playbook, ISO 27001 Gap Analysis Toolkit, Prompt Library, AI Workflows. Instant PDF download via Gumroad.{% endblock %}', c, count=1, flags=re.DOTALL)
c = re.sub(r'<meta property="og:title" content="[^"]*">',
           '<meta property="og:title" content="Cybersecurity & GRC eBooks - 5 Playbooks, $9 Each or $35 Bundle">', c, count=1)
c = re.sub(r'<meta property="og:description" content="[^"]*">',
           '<meta property="og:description" content="Instant-download PDFs by a working ISO 27001 auditor. $9 per playbook, or all five for $35 with the bundle.">', c, count=1)
c = re.sub(r'<meta name="twitter:title" content="[^"]*">',
           '<meta name="twitter:title" content="Cybersecurity & GRC eBooks - 5 Playbooks, $9 Each or $35 Bundle">', c, count=1)
c = re.sub(r'<meta name="twitter:description" content="[^"]*">',
           '<meta name="twitter:description" content="Instant-download PDFs by a working ISO 27001 auditor. $9 per playbook, or all five for $35 with the bundle.">', c, count=1)

# Book/ItemList schema with prices (commerce signal)
if 'application/ld+json' not in c or '"@type":"Book"' not in c:
    ld = '''<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "ItemList",
  "name": "Cybersecurity and GRC eBooks by Gaurav Malhotra",
  "itemListElement": [
    {"@type":"ListItem","position":1,"item":{"@type":"Book","name":"Breaking Into GRC: A Career-Changer's Guide","author":{"@type":"Person","name":"Gaurav Malhotra"},"offers":{"@type":"Offer","price":"9.00","priceCurrency":"USD","url":"https://malhotra72.gumroad.com/l/GRC"}}},
    {"@type":"ListItem","position":2,"item":{"@type":"Book","name":"Cybersecurity Prompt Library","author":{"@type":"Person","name":"Gaurav Malhotra"},"offers":{"@type":"Offer","price":"9.00","priceCurrency":"USD","url":"https://malhotra72.gumroad.com/l/Promptlibrary"}}},
    {"@type":"ListItem","position":3,"item":{"@type":"Book","name":"AI Workflows for Cybersecurity Professionals","author":{"@type":"Person","name":"Gaurav Malhotra"},"offers":{"@type":"Offer","price":"9.00","priceCurrency":"USD","url":"https://malhotra72.gumroad.com/l/cyberhustle"}}},
    {"@type":"ListItem","position":4,"item":{"@type":"Book","name":"The AI Governance Playbook","author":{"@type":"Person","name":"Gaurav Malhotra"},"offers":{"@type":"Offer","price":"9.00","priceCurrency":"USD","url":"https://malhotra72.gumroad.com/l/wxhxoo"}}},
    {"@type":"ListItem","position":5,"item":{"@type":"Book","name":"ISO 27001:2022 Gap Analysis & Certification Toolkit","author":{"@type":"Person","name":"Gaurav Malhotra"},"offers":{"@type":"Offer","price":"9.00","priceCurrency":"USD","url":"https://malhotra72.gumroad.com/l/Gapanalysis"}}},
    {"@type":"ListItem","position":6,"item":{"@type":"Book","name":"The Complete Cybersecurity Career Bundle","author":{"@type":"Person","name":"Gaurav Malhotra"},"offers":{"@type":"Offer","price":"35.00","priceCurrency":"USD","url":"https://malhotra72.gumroad.com/l/Cybersecuritybundle"}}}
  ]
}
</script>
'''
    i = c.find('{% block head %}')
    e = c.find('{% endblock %}', i)
    c = c[:e] + ld + c[e:]

open(p, "w", encoding="utf-8").write(c)
print("[UPDATED] /books -> buy-eBooks intent + Book schema")

subprocess.run(["git", "add", "-A"])
r = subprocess.run(["git", "commit", "-m", "SEO: separate intent - /resources free templates vs /books paid eBooks + Book schema"], capture_output=True, text=True)
print(f"\n[COMMIT] {r.stdout.strip() if r.returncode == 0 else r.stderr.strip()}")
r = subprocess.run(["git", "push", "origin", "main"], capture_output=True, text=True)
print("[PUSHED]" if r.returncode == 0 else f"[PUSH FAILED] {r.stderr}")
