import subprocess

p = "backend/templates/resources.html"
c = open(p, encoding="utf-8").read()

# 1. Remove the corrupted tail (broken endblock + misplaced script + stray })
idx = c.find("{% endblock %<script")
if idx >= 0:
    c = c[:idx] + "{% endblock %}\n"
    print("[FIXED] corrupted tail removed")
else:
    print("[CHECK] corrupted tail pattern not found")

# 2. Insert CollectionPage schema inside a proper head block after canonical
if "CollectionPage" not in c:
    ld = '''{% block head %}
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"CollectionPage","name":"Free Cybersecurity Templates & GRC Starter Kit","description":"Free, ready-to-use GRC artifacts generated by free tools.","url":"https://grcwithgaurav.com/resources"}
</script>
{% endblock %}
'''
    anchor = "{% block canonical %}https://grcwithgaurav.com/resources{% endblock %}"
    if anchor in c:
        c = c.replace(anchor, anchor + "\n" + ld, 1)
        print("[ADDED] head block with CollectionPage schema")
    else:
        print("[ERROR] canonical anchor not found")
        raise SystemExit(1)

open(p, "w", encoding="utf-8").write(c)

# 3. Parse check BOTH templates before committing
from jinja2 import Environment, FileSystemLoader
env = Environment(loader=FileSystemLoader("backend/templates"))
ok = True
for t in ["resources.html", "books.html"]:
    try:
        env.get_template(t)
        print(f"{t}: parses OK")
    except Exception as e:
        print(f"{t}: STILL BROKEN - {e}")
        ok = False
if not ok:
    raise SystemExit(1)

# 4. Commit + push
subprocess.run(["git", "add", "-A"])
r = subprocess.run(["git", "commit", "-m", "HOTFIX: repair broken endblock in resources.html, schema into head block"], capture_output=True, text=True)
print(f"\n[COMMIT] {r.stdout.strip() if r.returncode == 0 else r.stderr.strip()}")
r = subprocess.run(["git", "push", "origin", "main"], capture_output=True, text=True)
print("[PUSHED]" if r.returncode == 0 else f"[PUSH FAILED] {r.stderr}")
