import glob, subprocess
skip = ("venv", "node_modules", ".git")

# ========== 1. NEWSLETTER ENDPOINTS (append to analytics_routes) ==========
nl = '''

# ================= NEWSLETTER ENGINE (Resend) =================
import os as _os
import json as _nl_json
from urllib import request as _nl_req
from urllib.parse import quote as _nl_quote
from fastapi.responses import HTMLResponse as _NL_HTML
from fastapi import Request as _NL_Request
from fastapi import HTTPException as _NL_HTTP

NL_FROM = "Gaurav Malhotra <hello@grcwithgaurav.com>"

def _nl_send(messages):
    key = _os.environ.get("RESEND_API_KEY", "")
    if not key:
        return {"ok": False, "error": "RESEND_API_KEY not set"}
    url = "https://api.resend.com/emails/batch" if isinstance(messages, list) else "https://api.resend.com/emails"
    req = _nl_req.Request(url, data=_nl_json.dumps(messages).encode("utf-8"),
        headers={"Authorization": "Bearer " + key, "Content-Type": "application/json"}, method="POST")
    try:
        with _nl_req.urlopen(req, timeout=25) as resp:
            return {"ok": True, "status": getattr(resp, "status", 200)}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def _nl_ensure(db):
    from sqlalchemy import text as _t
    db.execute(_t("CREATE TABLE IF NOT EXISTS newsletter_subs (email TEXT UNIQUE, source TEXT, created_at TEXT, unsubscribed INTEGER DEFAULT 0)"))
    db.commit()

KIT_HTML = """<div style="font-family:Arial,sans-serif;background:#0a0a0a;color:#e0e0e0;padding:24px">
<h2 style="color:#00ffcc">Your Free Cybersecurity Starter Kit</h2>
<p>Five artifacts to start your security/GRC journey today - each generated by our free tools:</p>
<ol style="line-height:2.1">
<li><a href="https://grcwithgaurav.com/tools/risk-register-generator" style="color:#00ffcc">ISO 27001 Risk Register (CSV)</a></li>
<li><a href="https://grcwithgaurav.com/tools/iso-gap-assessment" style="color:#00ffcc">ISO 27001 Audit Checklist</a></li>
<li><a href="https://app.grcwithgaurav.com/questions/" style="color:#00ffcc">GRC Interview Questions (practice set)</a></li>
<li><a href="https://grcwithgaurav.com/app.html" style="color:#00ffcc">Cybersecurity Career Roadmap (6 months)</a></li>
<li><a href="https://grcwithgaurav.com/tools/ats-resume-checker" style="color:#00ffcc">Resume Template + ATS check</a></li>
</ol>
<p>Reply to this email if you want a personal nudge in the right direction.<br>- Gaurav</p>
<p style="font-size:12px;color:#888"><a href="https://grcwithgaurav.com/api/analytics/newsletter/unsubscribe?email=__UNSUB__" style="color:#888">Unsubscribe</a></p>
</div>"""

@router.post("/newsletter/subscribe")
def nl_subscribe(payload: dict, db: Session = Depends(get_db)):
    import re as _re
    from sqlalchemy import text as _t
    from datetime import datetime as _dt
    email = str((payload or {}).get("email", "")).strip().lower()[:200]
    source = str((payload or {}).get("source", "footer"))[:50]
    if not _re.match(r"^[\\w.+-]+@[\\w-]+\\.[\\w.]+$", email):
        return {"ok": False, "error": "Invalid email"}
    _nl_ensure(db)
    db.execute(_t("INSERT OR IGNORE INTO newsletter_subs (email, source, created_at, unsubscribed) VALUES (:e,:s,:c,0)"), {"e": email, "s": source, "c": _dt.utcnow().isoformat()})
    db.execute(_t("UPDATE newsletter_subs SET unsubscribed=0 WHERE email=:e"), {"e": email})
    db.commit()
    if source == "starter_kit":
        _nl_send({"from": NL_FROM, "to": [email], "subject": "Your Free Cybersecurity Starter Kit is inside", "html": KIT_HTML.replace("__UNSUB__", _nl_quote(email))})
    return {"ok": True}

@router.get("/newsletter/unsubscribe", response_class=_NL_HTML)
def nl_unsubscribe(email: str = "", db: Session = Depends(get_db)):
    from sqlalchemy import text as _t
    e = email.strip().lower()
    try:
        _nl_ensure(db)
        db.execute(_t("UPDATE newsletter_subs SET unsubscribed=1 WHERE email=:e"), {"e": e})
        db.commit()
    except Exception:
        pass
    return _NL_HTML("<html><body style='font-family:sans-serif;background:#0a0a0a;color:#e0e0e0;text-align:center;padding:4rem'><h2>You're unsubscribed.</h2><p>No hard feelings - the tools stay free forever.</p><p><a href='https://grcwithgaurav.com/' style='color:#00ffcc'>Back to GRCWithGaurav</a></p></body></html>")

@router.post("/newsletter/send")
def nl_send(payload: dict, request: _NL_Request, db: Session = Depends(get_db)):
    from sqlalchemy import text as _t
    from datetime import datetime as _dt
    secret = _os.environ.get("ADMIN_SECRET", "")
    if not secret or request.headers.get("x-admin-secret") != secret:
        raise _NL_HTTP(status_code=403, detail="Forbidden")
    subject = str((payload or {}).get("subject", ""))[:200]
    body = str((payload or {}).get("body_html", ""))[:200000]
    if not subject or not body:
        return {"ok": False, "error": "subject and body_html required"}
    _nl_ensure(db)
    rows = db.execute(_t("SELECT email FROM newsletter_subs WHERE unsubscribed=0")).fetchall()
    emails = [r[0] for r in rows]
    if not emails:
        return {"ok": True, "sent": 0, "total": 0}
    footer = "<p style='font-size:12px;color:#888'>You receive this because you subscribed at grcwithgaurav.com. <a href='https://grcwithgaurav.com/api/analytics/newsletter/unsubscribe?email=__UNSUB__' style='color:#888'>Unsubscribe</a>.</p>"
    sent = 0
    for i in range(0, len(emails), 50):
        chunk = emails[i:i+50]
        msgs = [{"from": NL_FROM, "to": [e], "subject": subject, "html": body.replace("__UNSUB__", _nl_quote(e)) + footer.replace("__UNSUB__", _nl_quote(e))} for e in chunk]
        r = _nl_send(msgs if len(msgs) > 1 else msgs[0])
        if r.get("ok"):
            sent += len(chunk)
    db.execute(_t("CREATE TABLE IF NOT EXISTS newsletter_log (created_at TEXT, subject TEXT, recipients INTEGER, status TEXT)"))
    db.execute(_t("INSERT INTO newsletter_log (created_at, subject, recipients, status) VALUES (:c,:s,:r,:st)"), {"c": _dt.utcnow().isoformat(), "s": subject, "r": sent, "st": "sent"})
    db.commit()
    return {"ok": True, "sent": sent, "total": len(emails)}
'''
ar = [x for x in glob.glob("**/analytics_routes.py", recursive=True) if not any(t in x for t in skip)][0]
c = open(ar, encoding="utf-8").read()
if "newsletter/subscribe" not in c:
    open(ar, "w", encoding="utf-8").write(c + nl)
    print("[BACKEND] newsletter endpoints added")

# ========== 2. Resources page: subscribe on kit request ==========
rh = [x for x in glob.glob("**/resources.html", recursive=True) if not any(t in x for t in skip)][0]
r = open(rh, encoding="utf-8").read()
old = 'fetch("/api/analytics/lead",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:em,source:"starter_kit"})}).catch(function(){});'
new = old + '\n  fetch("/api/analytics/newsletter/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:em,source:"starter_kit"})}).catch(function(){});'
if old in r and "newsletter/subscribe" not in r:
    open(rh, "w", encoding="utf-8").write(r.replace(old, new))
    print("[RESOURCES] kit request now subscribes + triggers kit email")

# ========== 3. Footer subscribe box ==========
bh = [x for x in glob.glob("**/base.html", recursive=True) if not any(t in x for t in skip)][0]
b = open(bh, encoding="utf-8").read()
if "nl-email" not in b:
    box = '''<div style="margin:1.8rem auto 0;max-width:440px">
        <div style="display:flex;gap:.5rem">
          <input id="nl-email" placeholder="Weekly GRC digest - free, no spam" style="flex:1;padding:.55rem .8rem;border-radius:8px;border:1px solid #333;background:#151515;color:#fff">
          <button id="nl-btn" style="background:var(--accent);color:#000;border:none;border-radius:8px;padding:.55rem 1rem;font-weight:700;cursor:pointer">Subscribe</button>
        </div>
        <p id="nl-msg" style="font-size:.78rem;color:#666;margin-top:.4rem"></p>
      </div>
      <script>
      document.getElementById("nl-btn").onclick=function(){
        var em=document.getElementById("nl-email").value.trim();
        var msg=document.getElementById("nl-msg");
        if(!em||em.indexOf("@")<1){ msg.style.color="#ef4444"; msg.textContent="Enter a valid email."; return; }
        fetch("/api/analytics/newsletter/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:em,source:"footer"})})
        .then(function(r){return r.json();}).then(function(d){
          if(d.ok){ msg.style.color="#22c55e"; msg.textContent="Subscribed. First digest lands Monday."; document.getElementById("nl-email").value=""; }
          else { msg.style.color="#ef4444"; msg.textContent=d.error||"Try again."; }
        }).catch(function(){ msg.style.color="#ef4444"; msg.textContent="Network error."; });
      };
      </script>
    </footer>'''
    b = b.replace("</footer>", box, 1)
    open(bh, "w", encoding="utf-8").write(b)
    print("[FOOTER] subscribe box added")

subprocess.run(["git", "add", "-A"])
subprocess.run(["git", "commit", "-m", "Newsletter engine: subscribe, kit delivery email, digest sender, unsubscribe"])
subprocess.run(["git", "push", "origin", "main"])
print("PUSHED")
