import os, json, subprocess

os.makedirs("backend/content", exist_ok=True)
if not os.path.exists("backend/content/books.json"):
    open("backend/content/books.json", "w", encoding="utf-8").write("[]")
    print("[CREATED] content/books.json (empty - fill with your ebooks, format below)")

# ---------- ABOUT ----------
about = """{% extends "base.html" %}
{% block title %}About Gaurav Malhotra | GRCWithGaurav{% endblock %}
{% block description %}Cybersecurity and GRC professional building practical tools, training and CyberVerse AI for security teams and job seekers.{% endblock %}
{% block content %}
<div style="max-width:800px;margin:0 auto;padding:2rem">
 <h1 style="color:#fff">Gaurav Malhotra</h1>
 <p style="color:var(--muted);font-size:1.05rem">Cybersecurity &amp; GRC professional. Founder of GRCWithGaurav and CyberVerse AI.</p>
 <div class="card" style="padding:1.5rem;margin-top:1.5rem">
  <h3 style="color:var(--accent)">What I build</h3>
  <ul style="color:#c9c9c9;line-height:1.8">
   <li><strong style="color:#fff">CyberVerse AI</strong> - AI mock interviews, resume rewrites and roadmaps for security job seekers.</li>
   <li><strong style="color:#fff">Free GRC tools</strong> - risk calculators, registers, policy drafts and Annex A references.</li>
   <li><strong style="color:#fff">Practical education</strong> - guides that turn frameworks into artifacts you can show in an interview.</li>
  </ul>
  <h3 style="color:var(--accent);margin-top:1.5rem">How I work</h3>
  <p style="color:#c9c9c9">Audit-ready evidence over paperwork theater. Every template, tool and guide here is built to survive a real auditor's questions - and a real interviewer's.</p>
 </div>
 <div style="display:flex;gap:1rem;margin-top:2rem;flex-wrap:wrap">
  <a href="/b2b" class="btn-primary">Work with me</a>
  <a href="/app.html" class="btn-secondary">Try CyberVerse AI</a>
 </div>
</div>
{% endblock %}"""
open("backend/templates/about.html", "w", encoding="utf-8").write(about)
print("[CREATED] about.html")

# ---------- RESOURCES (starter kit + books) ----------
resources = """{% extends "base.html" %}
{% block title %}Free Cybersecurity Resources & Starter Kit | GRCWithGaurav{% endblock %}
{% block description %}Free cybersecurity starter kit: ISO 27001 risk register, audit checklist, GRC interview questions, career roadmap and resume template - plus ebooks.{% endblock %}
{% block content %}
<div style="max-width:900px;margin:0 auto;padding:2rem">
 <h1 style="color:#fff">Resources</h1>
 <div class="card" style="padding:2rem;margin-top:1.5rem;border:1px solid var(--accent)">
  <h2 style="color:#fff;margin-top:0">FREE Cybersecurity Starter Kit</h2>
  <p style="color:var(--muted)">Five artifacts to start your security/GRC journey today - each generated by our free tools:</p>
  <ul style="color:#c9c9c9;line-height:1.9">
   <li>ISO 27001 Risk Register (CSV)</li>
   <li>ISO 27001 Audit Checklist (gap assessment)</li>
   <li>GRC Interview Questions (practice set)</li>
   <li>Cybersecurity Career Roadmap (6 months)</li>
   <li>Cybersecurity Resume Template (ATS-checked)</li>
  </ul>
  <div style="display:flex;gap:.6rem;margin-top:1rem;flex-wrap:wrap">
   <input id="kit-email" type="email" placeholder="you@domain.com" style="flex:1;min-width:220px;padding:.7rem;border-radius:8px;border:1px solid #333;background:#151515;color:#fff">
   <button class="btn-primary" id="kit-btn">Get the Free Kit</button>
  </div>
  <p id="kit-msg" style="font-size:.85rem;margin-top:.6rem"></p>
  <div id="kit-links" style="display:none;margin-top:1rem" class="card">
   <p style="margin:0 0 .5rem;color:var(--accent);font-weight:700">Your kit is ready:</p>
   <p style="margin:0;line-height:2">
    <a href="/tools/risk-register-generator">1. Risk Register &rarr;</a><br>
    <a href="/tools/iso-gap-assessment">2. Audit Checklist &rarr;</a><br>
    <a href="/app.html">3. GRC Interview Questions &rarr;</a><br>
    <a href="/app.html">4. Career Roadmap &rarr;</a><br>
    <a href="/tools/ats-resume-checker">5. Resume Template check &rarr;</a>
   </p>
  </div>
 </div>

 <h2 style="color:#fff;margin-top:3rem">Ebooks</h2>
 {% if books %}
 <div class="grid-3">
  {% for b in books %}
  <div class="card"><h3 style="font-size:1rem">{{ b.title }}</h3><p style="font-size:.85rem">{{ b.desc }}</p><a href="{{ b.link }}">Get the book &rarr;</a></div>
  {% endfor %}
 </div>
 {% else %}
 <p style="color:var(--muted)">Ebooks are being migrated to this platform. Check back shortly - or grab them via the CyberVerse AI app.</p>
 {% endif %}
</div>
<script>
document.getElementById("kit-btn").onclick=function(){
  var em=document.getElementById("kit-email").value.trim();
  if(!em || em.indexOf("@")<1){ document.getElementById("kit-msg").style.color="#ef4444"; document.getElementById("kit-msg").textContent="Enter a valid email."; return; }
  fetch("/api/analytics/lead",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:em,source:"starter_kit"})}).catch(function(){});
  document.getElementById("kit-msg").style.color="#22c55e"; document.getElementById("kit-msg").textContent="Kit unlocked below.";
  document.getElementById("kit-links").style.display="block";
};
</script>
{% endblock %}"""
open("backend/templates/resources.html", "w", encoding="utf-8").write(resources)
print("[CREATED] resources.html")

# ---------- CONTACT ----------
contact = """{% extends "base.html" %}
{% block title %}Contact | GRCWithGaurav{% endblock %}
{% block description %}Contact GRCWithGaurav for GRC consulting, ISO 27001 help, or CyberVerse AI support.{% endblock %}
{% block content %}
<div style="max-width:700px;margin:0 auto;padding:2rem;text-align:center">
 <h1 style="color:#fff">Contact</h1>
 <p style="color:var(--muted)">Two fast channels - pick yours:</p>
 <div class="grid-3" style="margin-top:2rem">
  <div class="card"><h3>Businesses</h3><p style="font-size:.88rem">ISO 27001 / SOC 2 / GRC help, consulting, enterprise CyberVerse.</p><a href="/b2b">Get a Free GRC Assessment &rarr;</a></div>
  <div class="card"><h3>Learners</h3><p style="font-size:.88rem">Interview prep, resume help, roadmaps and daily practice.</p><a href="/app.html">Open CyberVerse AI &rarr;</a></div>
 </div>
</div>
{% endblock %}"""
open("backend/templates/contact.html", "w", encoding="utf-8").write(contact)
print("[CREATED] contact.html")

# ---------- ROUTES + 301 REDIRECT MAP ----------
sr = "backend/routers/site_routes.py"
r = open(sr, encoding="utf-8").read()
if '"/about"' not in r:
    anchor = '@router.get("/sitemap.xml")'
    block = '''import json as _json

_BOOKS = []
try:
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "content", "books.json"), encoding="utf-8") as _bf:
        _BOOKS = _json.load(_bf)
except Exception:
    _BOOKS = []

@router.get("/about", response_class=HTMLResponse)
async def about_page(request: Request):
    return templates.TemplateResponse("about.html", {"request": request})

@router.get("/resources", response_class=HTMLResponse)
async def resources_page(request: Request):
    return templates.TemplateResponse("resources.html", {"request": request, "books": _BOOKS})

@router.get("/contact", response_class=HTMLResponse)
async def contact_page(request: Request):
    return templates.TemplateResponse("contact.html", {"request": request})

# 301 map: old-site URLs -> new equivalents (zero SEO loss at cutover)
_REDIRECTS = {"/books": "/resources", "/consulting": "/b2b", "/blog": "/learn", "/home": "/", "/about-us": "/about"}

def _make_redir(target):
    async def _r(request: Request):
        return RedirectResponse(url=target, status_code=301)
    return _r

for _old, _new in _REDIRECTS.items():
    router.add_api_route(_old, _make_redir(_new), methods=["GET"], include_in_schema=False)

'''
    r = r.replace(anchor, block + anchor)
    open(sr, "w", encoding="utf-8").write(r)
    print("[ROUTES] /about /resources /contact + 301 map added")

subprocess.run(["git", "add", "-A"])
subprocess.run(["git", "commit", "-m", "Cutover stage 1: about/resources/contact pages + 301 redirect map"])
subprocess.run(["git", "push", "origin", "main"])
print("Pushed. Stage 1 live in ~60s.")
