"""add emailed_at to daily_bundles

Revision ID: ed960241d72c
Revises: 9608b5f05ed1
Create Date: 2026-08-08 00:07:23.543857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed960241d72c'
down_revision: Union[str, None] = '9608b5f05ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_bundles', sa.Column('emailed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_bundles', 'emailed_at')
    # ### end Alembic commands ###
